version: '3.6'

services: 
  server:
    container_name: server 
    build: 
      context: .
    env_file:
      - .env.prod
    depends_on: 
      - postgres
    volumes:
      - "/home/gemma_cosmetic:/app/dist/static"
    ports: 
      - 5000:5000
  
  postgres:
    container_name: postgres
    image: postgres
    env_file: 
      - .env.prod
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes: 
  pgdata:
