version: '3.5'

services: 
  server:
    container_name: server 
    build: 
      context: .
    env_file:
      - .env.prod
    depends_on: 
      - postgres
    ports: 
      - 5000:5000
    volumes:
      - type: volume
        source: static
        target: /src/static
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    env_file: 
      - .env.prod
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: always

volumes: 
  pgdata:
  static: