version: '3.8'

services: 
  server:
    build: 
      context: .
    depends_on: 
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    env_file: 
      - .env
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  nginx:
    build: 
      context: ./nginx
    ports: 
      - 5000:5000

volumes: 
  pgdata: